ALTER TABLE questions
ADD COLUMN IF NOT EXISTS domain TEXT,
ADD COLUMN IF NOT EXISTS reference_answer TEXT,
ADD COLUMN IF NOT EXISTS answer_key_points JSONB NOT NULL DEFAULT '[]',
ADD COLUMN IF NOT EXISTS category_id INTEGER REFERENCES training_categories(id);

CREATE TABLE IF NOT EXISTS domains (
  id SERIAL PRIMARY KEY,
  name VARCHAR(120) NOT NULL UNIQUE,
  description TEXT,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);