import React, { useEffect, useRef, useState } from 'react';

const API = import.meta.env.VITE_API_URL || 'http://localhost:4000/api';
async function api(path, options = {}) {
  const response = await fetch(API + path, options);
  if (!response.ok) throw new Error((await response.json()).error || 'Request failed');
  return response.status === 204 ? null : response.json();
}

function Setup({ start, admin }) {
  const [form, setForm] = useState({ interviewType: 'technical', role: 'backend-developer', difficulty: 'beginner', questionCount: 3 });
  const change = (e) => setForm({ ...form, [e.target.name]: e.target.value });
  return <main className="card narrow"><h1>Interview AI</h1><p>Start an adaptive video interview.</p>{['interviewType', 'role', 'difficulty', 'questionCount'].map((field) => <label key={field}>{field}<input name={field} value={form[field]} type={field === 'questionCount' ? 'number' : 'text'} onChange={change} /></label>)}<button onClick={() => start(form)}>Start interview</button><button className="secondary" onClick={admin}>Admin question bank</button></main>;
}

function Live({ interview, complete }) {
  const video = useRef(); const recorder = useRef(); const stream = useRef();
  const [position, setPosition] = useState(0); const [prompt, setPrompt] = useState(interview.questions[0].text); const [recording, setRecording] = useState(false); const [status, setStatus] = useState('Requesting camera and microphone…'); const [parent, setParent] = useState(null);
  useEffect(() => { navigator.mediaDevices.getUserMedia({ video: true, audio: true }).then((value) => { stream.current = value; video.current.srcObject = value; setStatus('Ready'); }).catch(() => setStatus('Camera and microphone permission is required.')); return () => stream.current?.getTracks().forEach((track) => track.stop()); }, []);
  const poll = async (id) => { const answer = await api(`/answers/${id}`); if (answer.status === 'failed') { setStatus(`Analysis failed: ${answer.error_message || 'check backend logs'}`); return; } if (answer.status !== 'analyzed') return setTimeout(() => poll(id), 1500); const report = await api(`/analysis/interviews/${interview.id}/report`); const result = report.answers.find((item) => item.answer_id === id)?.result; if (result?.needsFollowUp) { setParent(id); setPrompt(result.followUpQuestion); setStatus('Follow-up question'); return; } if (position + 1 < interview.questions.length) { setPosition(position + 1); setParent(null); setPrompt(interview.questions[position + 1].text); setStatus('Next question'); } else { await api(`/interviews/${interview.id}/finish`, { method: 'POST' }); complete(interview.id); } };
  const stop = () => recorder.current.stop();
  const start = () => { const chunks = []; recorder.current = new MediaRecorder(stream.current); recorder.current.ondataavailable = (event) => chunks.push(event.data); recorder.current.onstop = async () => { setRecording(false); setStatus('Analyzing answer…'); const data = new FormData(); data.append('video', new Blob(chunks, { type: 'video/webm' }), 'answer.webm'); data.append('interviewQuestionId', interview.questions[position].interview_question_id); if (parent) data.append('parentAnswerId', parent); const answer = await api(`/interviews/${interview.id}/answers`, { method: 'POST', body: data }); poll(answer.id); }; recorder.current.start(); setRecording(true); setStatus('Recording…'); };
  return <main className="card live"><span>{status}</span><h2>Question {position + 1} of {interview.questions.length}</h2><video ref={video} autoPlay muted playsInline /><h1>{prompt}</h1><p>Your answer is submitted automatically when you stop recording.</p>{recording ? <button className="danger" onClick={stop}>Stop recording</button> : <button onClick={start} disabled={!stream.current}>Start recording</button>}</main>;
}

function Report({ id, home }) { const [report, setReport] = useState(); useEffect(() => { api(`/analysis/interviews/${id}/report`).then(setReport); }, [id]); if (!report) return <main className="card"><h2>Loading report…</h2></main>; return <main className="card"><h1>Interview report</h1><div className="scores">{Object.entries(report.scores).map(([name, score]) => <div key={name}><strong>{score}</strong><small>{name}</small></div>)}</div>{report.answers.map((answer, index) => <article className="feedback" key={`${answer.answer_id}-${index}`}><h3>{index + 1}. {answer.question}</h3><pre>{JSON.stringify(answer.result, null, 2)}</pre></article>)}<button onClick={home}>New interview</button></main>; }

function Admin({ home }) { const [questions, setQuestions] = useState([]); const [text, setText] = useState(''); const load = () => api('/questions?isActive=true').then(setQuestions); useEffect(load, []); const add = async (event) => { event.preventDefault(); await api('/questions', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ interviewType: 'technical', role: 'backend-developer', difficulty: 'beginner', text, expectedTopics: [] }) }); setText(''); load(); }; return <main className="card"><button className="link" onClick={home}>Back</button><h1>Admin question bank</h1><form onSubmit={add}><input required value={text} onChange={(e) => setText(e.target.value)} placeholder="Question text" /><button>Add question</button></form>{questions.map((question) => <div className="row" key={question.id}>{question.text}<button className="danger" onClick={async () => { await api(`/questions/${question.id}`, { method: 'DELETE' }); load(); }}>Delete</button></div>)}</main>; }

export default function App() { const [page, setPage] = useState('setup'); const [interview, setInterview] = useState(); const [reportId, setReportId] = useState(); const start = async (form) => { try { setInterview(await api('/interviews', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) })); setPage('live'); } catch (error) { alert(error.message); } }; if (page === 'admin') return <Admin home={() => setPage('setup')} />; if (page === 'live') return <Live interview={interview} complete={(id) => { setReportId(id); setPage('report'); }} />; if (page === 'report') return <Report id={reportId} home={() => setPage('setup')} />; return <Setup start={start} admin={() => setPage('admin')} />; }
